---
- name: "Installing Wordpress"
  become: true
  hosts: amazon
  vars_files:
    - virtualhost-template       
  vars:
    httpd_owner: "apache"
    httpd_group: "apache"
    httpd_port: 80
    httpd_domain: "blog.pratheeshsatheeshkumar.online"
    httpd_docroot: "/var/www/html/"
    mariadb_root_password: "mysqlroot123"
    mariadb_extra_user: "bloguser"
    mariadb_extra_user_password: "bloguser123"
    mariadb_extra_database: "blogdatabase"
    wp_url: "https://wordpress.org/wordpress-6.0.3.tar.gz"
  tasks:

    - name: "Apache: Installing Apache Webserver"
      yum:
        name: httpd
        state: present
      tags:
        - lamp 
        
    - name: "Apache: Enabling php support"
      shell: amazon-linux-extras install php7.4 -y
      tags:
        - lamp 

    - name: "Apache: Creating httpd.conf from httpd.conf.j2"
      template:
        src: ./httpd.conf.j2 
        dest: /etc/httpd/conf/httpd.conf
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      tags:
        - lamp 

    - name: "Apache: Creating virtualhost.conf from virtualhost.conf.j2"
      template:
        src: ./virtualhost.conf.j2
        dest: "/etc/httpd/conf.d/{{ httpd_domain }}.conf"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
