---
- name: "Installing Wordpress"
  become: true
  hosts: amazon
  vars:
    httpd_owner: "apache"
    httpd_group: "apache"
    httpd_port: 80
    httpd_domain: "blog.pratheeshsatheeshkumar.online"
    httpd_docroot: "/var/www/html/"
    mariadb_root_password: "mysqlroot123"
    mariadb_extra_user: "bloguser"
    mariadb_extra_user_password: "bloguser123"
    mariadb_extra_database: "blogdatabase"
    wp_url: "https://wordpress.org/wordpress-6.0.3.tar.gz"
  tasks:

    - name: "Apache: Installing Apache Webserver"
      yum:
        name: httpd
        state: present
      tags:
        - lamp 
        
    - name: "Apache: Enabling php support"
      shell: amazon-linux-extras install php7.4 -y
      tags:
        - lamp 

    - name: "Apache: Creating httpd.conf from httpd.conf.j2"
      template:
        src: ./httpd.conf.j2 
        dest: /etc/httpd/conf/httpd.conf
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      tags:
        - lamp 

    - name: "Apache: Creating virtualhost.conf from virtualhost.conf.j2"
      template:
        src: ./virtualhost.conf.j2
        dest: "/etc/httpd/conf.d/{{ httpd_domain }}.conf"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
        
    - name: "Apache: Removing previous contents of docroot"
      file:
        path: "{{ httpd_docroot }}"      
        state: absent
      tags:
        - lamp 

    - name: "Apache: Creating docroot at {{ httpd_docroot }}{{ httpd_domain}} "  
      file:
        path: "{{ httpd_docroot }}{{ httpd_domain}}"
        state: directory
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}" 
      tags:
        - lamp 
    - name : "Apache: Restarting httpd service"  
      service:
        name: httpd
        state: restarted
        enabled: true   
      tags:
        - lamp
    
    - name: "MariaDB: MariaDB server package installation"
      yum:
        name: 
          - mariadb-server
          - MySQL-python          
        state: present
      tags:
        - lamp 
        - mariadb   
        
    - name: "MariaDB: Restart MariaDB service and enable"
      service:
        name: mariadb
        state: restarted
        enabled: true
      tags:
        - lamp 
        - mariadb  
        
    - name: "MariaDB: Setting root user password as {{ mariadb_root_password }}"
      ignore_errors: true
      mysql_user: 
        login_user: "root"
        login_password: ""
        name: "root"
        password: "{{ mariadb_root_password }}"   
        host_all: true
      tags:
        - lamp 
        - mariadb

    - name: "MariaDB: Removal of anonimous users"
      mysql_user: 
        login_user: "root"
        login_password: "{{ mariadb_root_password }}"
        name: ""
        password: ""
        host_all: true    
        state: absent   
      tags:
        - lamp 
        - mariadb

    - name: "MariaDB: Creating extra db"
      mysql_db: 
        login_user: "root"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ mariadb_extra_database }}"
        state: present
      tags:
        - lamp 
        - mariadb

    - name: "MariaDB: Creating extra user"
      mysql_user: 
        login_user: "root"
        login_password: "{{ mariadb_root_password }}"
        user: "{{ mariadb_extra_user }}"
        password: "{{ mariadb_extra_user_password }}"
        state: present
        host: "%"
        priv: "{{ mariadb_extra_database }}.*:ALL"   
      tags:
        - lamp 
        - mariadb 
